### PR TITLE
Doc: Adding documentation website

### PR DESCRIPTION
**Pull request by aryan-rajoria**
PR involves adding a documentation website for dep-scan.
Uses the docusaurus framework.

### CODE REVIEW

**Comment by aryan-rajoria** [comment]
Continuous deployment of the changes:
[delightful-cat-6f4f84.netlify.app](https://delightful-cat-6f4f84.netlify.app/)

**Review by prabhu — COMMENTED** [review]
Can we remove the many docusaurus icons in the static directory?

**Review by prabhu — APPROVED** [review]
Thank you so much!

**Comment by prabhu** [comment]
Can you share the readthedocs url so that we can create a cname alias and add to the repo?

**Pull request merged**
