### PR TITLE
feat: add version flag

### LINKED ISSUE #121: Version of depscan
Hi! It would be nice to have a `-v` or `--version` flag in the binary so that I can view the version of depscan I am using. An enhancement over this could be to store the version of the depscan in [reports](https://github.com/ASSERT-KTH/sbom.exe/blob/main/watchdog-agent/src/test/resources/pdfbox-3.0.0/sbom-universal.json) generated by it.

### PR DESCRIPTION
**Pull request by algomaster99**
Fixes #121 

I have added the function for getting the version. Could you point in the code where do I need to edit the metadata?

### CODE REVIEW

**Comment by prabhu** [comment]
Wow, this is super fast!!!

We can update the metadata here.

https://github.com/owasp-dep-scan/dep-scan/blob/master/depscan/cli.py#L386

**Comment by algomaster99** [comment]
@prabhu done!

Two things need to be done:
1. Update test resources
2. Add `pURL` and other attributes as listed [here](https://cyclonedx.org/docs/1.5/json/#metadata_tools_oneOf_i0_components).

**Comment by prabhu** [comment]
Thank you so much. @cerrussell, could you kindly take a look?

**Review by cerrussell — APPROVED** [review]

**Comment by cerrussell** [comment]
@prabhu Looks good to me, thanks @algomaster99 !

**Pull request merged**
