### PR TITLE
Adding the option to pass required-only argument to cdxgen

### PR DESCRIPTION
**Pull request by deleterepo**
Passing "--required-only" argument to cdxgen when the argument is included when running depscan. 

Argument passed successfully to cdxgen:
image

"@typescript-eslint" dependency no longer showing up in `bom.vdr.json` for a scan against Juice Shop:
image

### CODE REVIEW

**Comment by prabhu** [comment]
@deleterepo Thank you! I think this is very good idea. Can we consider making this a bit generic to accept `CDXGEN_ARGS` as an environment variable or via cli? This way many more options could be passed easily without the need for mirroring them in depscan.

**Comment by deleterepo** [comment]
Hi @prabhu! Yes absolutely I'll make that change soon.

**Comment by deleterepo** [comment]
Ok @prabhu @cerrussell I updated this to have a generic cdxgen-args argument. It can be populated in two ways:

With the `--cdxgen-args` argument:
image

or

 With the `CDXGEN_ARGS` environment variable:
image

**Review by prabhu — APPROVED** [review]
Thank you so much! Could you kindly create another PR against master branch, since the master branch is for v6 which will be released end of this year.

**Comment by prabhu** [comment]
@deleterepo Sorry if it was confusing. We need two PRs. One against master and one against release/5.x. The branches have to be created correctly from those base branches.

**Comment by deleterepo** [comment]
Got it will do

**Review by prabhu — APPROVED** [review]

**Pull request closed without merging**
